### ISSUE TITLE
复制粘贴功能设计讨论

### ISSUE THREAD

**Issue by yaming116** [openatx/android-uiautomator-server#37]
需求来源 https://github.com/openatx/uiautomator2/issues/438

在`AutomatorService` 添加两个接口如下:

```java
void setClipboard(String label, String text);

String getClipboard();
```
查看[ClipData](https://developer.android.com/reference/android/content/ClipData?hl=en#newHtmlText(java.lang.CharSequence,%20java.lang.CharSequence,%20java.lang.String)) api文档之后发现会有5中数据类型可以放在粘贴板中,目前直接做一种还是全部都需要实现

具体使用的[demo 可以看这里](https://www.programcreek.com/java-api-examples/?api=android.content.ClipboardManager)

**Comment by codeskyblue** [comment]
可以，提pr吧




            
            
                
                    
                            
                                
                            
                            
                                命令行
                            
                    
                        
                            
                                    邮箱：codeskyblue@gmail.com
                            
                        
                
            
        签名由 网易邮箱大师 定制


在2019年10月08日 16:09，孙善明 写道： 需求来源 openatx/uiautomator2#438

在AutomatorService 添加两个接口如下:
void setClipboard(String label, String text);

String getClipboard();
查看ClipData api文档之后发现会有5中数据类型可以放在粘贴板中,目前直接做一种还是全部都需要实现
具体使用的demo 可以看这里

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/openatx/android-uiautomator-server/issues/37?email_source=notifications\u0026email_token=AAZBGGIJEXPAYI5H3WNJEDLQNQ52JA5CNFSM4I6OL5I2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HQIZOFA",
"url": "https://github.com/openatx/android-uiautomator-server/issues/37?email_source=notifications\u0026email_token=AAZBGGIJEXPAYI5H3WNJEDLQNQ52JA5CNFSM4I6OL5I2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HQIZOFA",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by mingyuan-xia** [comment]
估计做plain text 确保中文即可，code放个TODO ClipData还有五种其他估计目前就够了
