### ISSUE TITLE
app-uiautomator客户端，点击启动uiautomator时会闪退

### ISSUE THREAD

**Issue by alloovee** [openatx/android-uiautomator-server#40]
app-uiautomator客户端，点击启动uiautomator时，会提示启动成功，但过两三秒，app就闪退。
重启app还是显示 uiautomator stopped。

说明：
1、用release 2.0.4的打好的包，启动ua服务会闪退，但重启app显示已启动。uiautomator服务不稳定，跑一两个用例就stopped了
2、用源码debug，启动ua服务会闪退，重启app依然显示stopped
3、atx-agent用的是默认安装版本
4、经过调试，startUiautomator是执行成功的，但过两三秒app就闪退，也捕获不到异常信息；
5、以上测试机型：华为荣耀10青春版、红米6、红米6、360

**Comment by codeskyblue** [comment]
Python iautomator 2版本多少




            
            
                
                    
                            
                                
                            
                            
                                命令行
                            
                    
                        
                            
                                    邮箱：codeskyblue@gmail.com
                            
                        
                
            
        签名由 网易邮箱大师 定制


在2019年11月29日 10:55，alloovee 写道： app-uiautomator客户端，点击启动uiautomator时，会提示启动成功，但过两三秒，app就闪退。
重启app还是显示 uiautomator topped。
说明：
1、用release 2.0.4的打好的包，启动ua服务会闪退，但重启app显示已启动。uiautomator服务不稳定，跑一两个用例就stopped了
2、用源码debug，启动ua服务会闪退，重启app依然显示stopped
3、atx-agent用的是默认安装版本
4、经过调试，startUiautomator是执行成功的，但过两三秒app就闪退，也捕获不到异常信息；
5、以上测试机型：华为荣耀10青春版、红米6、红米6、360

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/openatx/android-uiautomator-server/issues/40?email_source=notifications\u0026email_token=AAZBGGJZZX6O62JQRP4ODXTQWCAALA5CNFSM4JS2I44KYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4H4ZFUBA",
"url": "https://github.com/openatx/android-uiautomator-server/issues/40?email_source=notifications\u0026email_token=AAZBGGJZZX6O62JQRP4ODXTQWCAALA5CNFSM4JS2I44KYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4H4ZFUBA",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by alloovee** [comment]
1、uiautomator2 是下载最新的源码运行的
2、atx-agent 0.8.0
3、Python 3.6.2

**Comment by alloovee** [comment]
破案了。经过查看atx-agent日志，发现是uiautomator.apk 与 uiautomator.test.apk 签名不一致导致。
因为我debug的时候，只安装了前者。后来两个同时安装上，就没有闪退的问题了。

**Comment by codeskyblue** [comment]
good

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
